### ISSUE TITLE
Why sub-domains are not covered implicitly

### ISSUE THREAD

**Issue by aakashysharma** [linuxmint/mintnanny#13]
Version 1.4.8

I've configured domain blocker (mintnanny) to stop some specific domains, in this example let's consider amazon.de

If I open amazon.de, it's not accessible. However, some domains have redirects and render https pages. So, those are not blocked. My (_maybe wrong_) understanding is that if I block a domain, it should block it, irrespective of whether it's accessed by https or not. 

Do I need to provide different URL such as *.amazon.de to block it completely?

![screenshot at 2016-10-31 14 44 29](https://cloud.githubusercontent.com/assets/1897100/19856351/58b8fd04-9f79-11e6-97be-82275d072ca2.png)

**Comment by clefebvre** [comment]
@aakashysharma try to add www.amazon.de as well.

**Comment by aakashysharma** [comment]
Sure, adding www.amazon.de blocks it. However, not sure if adding **www.amazon.de** for blocking all sub-domains of **amazon.de** is correct idea.

The name, "Domain" blocker gives the impression that amazon.de should be enough. For example, there might be many cdn servers with different sub-domain names. For example, for facebook which runs <servername>.fbcdn.com. 

I tried, *.somedomain.com but that's not accepted.
