### ISSUE TITLE
Titlebar uses nonexistent icon

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintnanny#15]
I'm using one of the color variations of the Mint-X icon theme.  The title bar of the Domain Blocker window has a red circle-slash icon meaning "icon not found," although the global Apps menu and the window-list applet in the Panel have a suitable icon for this app.  

It could be suggested that the red circle-slash is appropriate for the domain blocker.  However, this particular icon has a black background & a white border around it, and is the same icon used whenever an icon isn't found.  Therefore, it gives the impression that this icon wasn't chosen on purpose.  A red circle-slash without the background might be OK, or an "Earth globe" icon.  

LMDE 2 Betsy, Cinnamon.  `mintnanny` APT package version 1.5.2.

**Comment by xenopeek** [comment]
I can't reproduce this on the LMDE 2 refresh from March 13 2017, using Mint-X-Aqua.
