### ISSUE TITLE
Changes not recognzed if site has alrready been visited

### ISSUE THREAD

**Issue by jelabarre59** [linuxmint/mintnanny#17]
This will not clear out the existing DNS entry if you add a hostname after someone has already browsed to the website.  In order to have immediate results it needs to also purge the DNS cache.

**Comment by xenopeek** [comment]
Thanks for contributing to mintnanny.

This isn't an issue that can be solved in mintnanny. Programs that consult the /etc/hosts file, which is what mintnanny uses to block domain names, will immediately after adding a domain to the block list see this change. Like if you try a ping or wget on a blocked domain you see it resolves to localhost (127.0.0.1). As such mintnanny is working correctly and there is no DNS cache to purge.

Some programs keep their own runtime DNS cache, like your web browser probably. You will most likely have to restart the web browser to clear its runtime DNS cache.

Linux Mint uses dnsmasq to correctly handle DNS requests when connecting to a VPN. dnsmasq by default runs in non-caching mode (`--cache-size=0`) but it also runs without reading the hosts file (`--no-hosts`). That means that programs that don't consult the /etc/hosts file will still be able to resolve the domain's IP address. For example with the `dig blockeddomain.com` command. That's not something that can be resolved in mintnanny.

**Comment by jelabarre59** [comment]
I was thinking more in terms that Mintnanny would have to have an additional function of flushing the DNS cache as well as managing the blocked list.  Otherwise I can just as readily SSH into the system and run a command or script to switch out hosts files, then run a "killall <browser name" to clear it's own route information.  Actually would work better at the router itself, but home routers are horribly inflexible, no dynamic reconfiguration there.

**Comment by xenopeek** [comment]
> Otherwise I can just as readily SSH into the system and run a command or script to switch out hosts files, then run a "killall <browser name" to clear it's own route information.

That doesn't solve that programs that don't consult the /etc/hosts file will still be able to resolve IP addresses of blocked domains.
