### ISSUE TITLE
Blacklist add, automatic renew option

### ISSUE THREAD

**Issue by edmundlaugasson** [linuxmint/mintnanny#7]
It would be great to have opportunity to add some existing blacklist(s) and mintnanny would update them periodically.
E.g. http://askubuntu.com/questions/44487/wheres-the-gnome-nanny-blacklist-repo
If there is no good and well maintained blacklist - perhaps mintnanny should start its own? But I really hope there are some.

**Comment by clefebvre** [comment]
It's a bit beyond the scope, but we could... the problem as you said is that we lack reliable sources.
