### ISSUE TITLE
Limiting time with mintnanny

### ISSUE THREAD

**Issue by edmundlaugasson** [linuxmint/mintnanny#8]
There would be also time limiting feature expected.
Like Timekpr has - http://www.omgubuntu.co.uk/2014/05/timekpr-restrict-computer-access-ubuntu
Certainly - we can use Timekpr but such feature would also be added. This could be done also using PAM.
In LightDM I did so:
* added into /etc/pam.d/lightdm the last row: account required pam_time.so
* into /etc/security/time.conf added "*;*;user1|user2;Al0600-2200" (without quotes) - this means from 6 AM till 10 PM allowed to log in users user1 and user2 - here is an example how to add multiple users with | sign.
* into /etc/crontab I added "0 22    * * *    root    pkill -9 -u user1" (without quotes) to kick out the mentioned user(s) at the required time. Each user need its own row into /etc/crontab

Do not know does it work under MDM (/etc/pam.d/mdm exist - so there is a hope) but at least the idea is here as one possibility how to solve this. Do not know, what technique the Timekpr uses but you could look also into its source code - https://launchpad.net/timekpr - possibly they could have better solution.
Timekpr is just an example how there could be solved the GUI design.
In addition blocking addresses, we have also problem with kids sitting in computer at the night.
One more thing - when there will be guest user (https://github.com/linuxmint/mdm/issues/51) - the time restriction should work also for guest user. Or if it is not possible (which I hope is not true) then the mintnanny should say that and offer to disable guest user.
Also there would be expected the domain addresses blocking should work globally or there should be opportunity to configure so. Currently there is not clear - will blocked addresses have effect only for current user or all users (including future's guest user).

**Comment by clefebvre** [comment]
That's beyond the scope for mintnanny unfortunately.
